Fix German plural of Dummy
valentjn/languagetool-languageserver pull request #178
Opened 2022-07-27 11:29 UTC by sfo

In German, the plural form of Dummy is Dumm**y**s, not Dumm**ie**s, which instead triggers a false positive:

![ltex_dummies](https://user-images.githubusercontent.com/571497/181236128-b0d37fc9-4228-434d-8e9d-b287480a5c75.png)

2022-07-27 13:36 UTC, valentjn commented
`de` is not the only German language in LanguageTool. At least `de-DE` (which should be preferred over `de`) is missing, plus all other variants of German for which this is applicable.

2022-07-27 18:41 UTC, valentjn requested changes
See above. Looks good otherwise.

2022-08-01 10:00 UTC, sfo commented
Thanks for reviewing @valentjn. I adapted the patch accordingly.

2023-02-12 11:14 UTC, valentjn commented
Fixed in 85fd1f250d4e7d4dd0a77b2cf5c6b9c6dd9167b6.

2023-02-12 11:14 UTC, closed without merging